# Kitty Configuration

# Enable transparency
background_opacity 0.85
background #2d353b

# Allow Hyprland to control opacity
dynamic_background_opacity yes

# Performance Optimizations
update_check_interval 0
shell_integration enabled
